In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/kinetic/corr_df_N2N.csv", sep=",", header=0, index_col='index')
df.head()

            RDm1
index
x_s     0.376445
time_s  0.376445
Temp   -0.812568
X1     -0.994226
X2      0.715481

In [36]:
df11 = df.rename(columns={"index": "features", "RDm1": "Pearson Correlation"})

In [37]:
df12 = df11.drop(index='RDm1')

In [47]:
df11

        Pearson Correlation
index
x_s                0.376445
time_s             0.376445
Temp              -0.812568
X1                -0.994226
X2                 0.715481
X3                 0.868037
X4                 0.822936
X5                 0.748769
X6                 0.669713
X7                 0.593591
X8                 0.523748
X9                 0.461424
X10                0.406712
X11                0.359125
X12                0.317920
X13                0.282299
X14                0.251495
X15                0.224820
X16                0.201674
X17                0.181544
X18                0.163998
X19                0.148672
X20                0.135263
X21                0.123515
X22                0.113219
X23                0.104197
X24                0.096303
X25                0.089419
X26                0.083446
X27                0.078307
X28                0.073943
X29                0.070313
X30                0.067395
X31                0.065187
X32                0.063715
X33                0.063036
X34                0.063254
X35                0.064535
X36                0.067143
X37                0.071486
X38                0.078202
X39                0.088306
X40                0.103438
X41                0.126329
X42                0.161608
X43                0.217067
X44                0.304378
X45                0.432063
X46                0.573363
X47                0.654592
X48                0.654544
rho                0.789155
v                 -0.849481
p                  0.849481
RDm1               1.000000

In [39]:
df1 = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/kinetic/Lasso_N2N.csv", sep=",", header=0, index_col='index')
df1.head()

            LassoCV
index
0      1.582578e+17
1      0.000000e+00
2      1.060626e+20
3      0.000000e+00
4      0.000000e+00

In [40]:
df3 = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/kinetic/SelectFromModel.csv", sep=",", header=0, index_col='index')
df3.head()

        SelectFromModel
index
x_s            0.001709
time_s         0.003892
Temp           0.173702
X1             0.010221
X2             0.001448

In [41]:
df4 = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/kinetic/RFE_N2N.csv", sep=",", header=0, index_col='index')
df4.head()

       RFE
index
0        1
1        3
2        1
3        2
4        5

In [48]:
dm = pd.concat([df12,df3], axis=1)

In [49]:
dm

        Pearson Correlation  SelectFromModel
index
x_s                0.376445         0.001709
time_s             0.376445         0.003892
Temp              -0.812568         0.173702
X1                -0.994226         0.010221
X2                 0.715481         0.001448
X3                 0.868037         0.001161
X4                 0.822936         0.001184
X5                 0.748769         0.005110
X6                 0.669713         0.009755
X7                 0.593591         0.006106
X8                 0.523748         0.009780
X9                 0.461424         0.011210
X10                0.406712         0.009259
X11                0.359125         0.007731
X12                0.317920         0.007962
X13                0.282299         0.000905
X14                0.251495         0.002239
X15                0.224820         0.004971
X16                0.201674         0.003496
X17                0.181544         0.002470
X18                0.163998         0.001623
X19                0.148672         0.007484
X20                0.135263         0.004019
X21                0.123515         0.002697
X22                0.113219         0.001642
X23                0.104197         0.003990
X24                0.096303         0.003129
X25                0.089419         0.003291
X26                0.083446         0.002782
X27                0.078307         0.002721
X28                0.073943         0.000274
X29                0.070313         0.002775
X30                0.067395         0.003327
X31                0.065187         0.000018
X32                0.063715         0.014871
X33                0.063036         0.000591
X34                0.063254         0.000901
X35                0.064535         0.000352
X36                0.067143         0.000150
X37                0.071486         0.000137
X38                0.078202         0.001294
X39                0.088306         0.000191
X40                0.103438         0.000088
X41                0.126329         0.000163
X42                0.161608         0.000488
X43                0.217067         0.000000
X44                0.304378         0.000000
X45                0.432063         0.000000
X46                0.573363         0.000000
X47                0.654592         0.000000
X48                0.654544              NaN
rho                0.789155         0.423884
v                 -0.849481         0.137036
p                  0.849481         0.105770

In [43]:
dm1 = dm.loc[('X48','SelectFromModel')] = 0

In [44]:
dm  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        Pearson Correlation  SelectFromModel
index
x_s                0.376445         0.001709
time_s             0.376445         0.003892
Temp              -0.812568         0.173702
X1                -0.994226         0.010221
X2                 0.715481         0.001448
X3                 0.868037         0.001161
X4                 0.822936         0.001184
X5                 0.748769         0.005110
X6                 0.669713         0.009755
X7                 0.593591         0.006106
X8                 0.523748         0.009780
X9                 0.461424         0.011210
X10                0.406712         0.009259
X11                0.359125         0.007731
X12                0.317920         0.007962
X13                0.282299         0.000905
X14                0.251495         0.002239
X15                0.224820         0.004971
X16                0.201674         0.003496
X17                0.181544         0.002470
X18                0.163998         0.001623
X19                0.148672         0.007484
X20                0.135263         0.004019
X21                0.123515         0.002697
X22                0.113219         0.001642
X23                0.104197         0.003990
X24                0.096303         0.003129
X25                0.089419         0.003291
X26                0.083446         0.002782
X27                0.078307         0.002721
X28                0.073943         0.000274
X29                0.070313         0.002775
X30                0.067395         0.003327
X31                0.065187         0.000018
X32                0.063715         0.014871
X33                0.063036         0.000591
X34                0.063254         0.000901
X35                0.064535         0.000352
X36                0.067143         0.000150
X37                0.071486         0.000137
X38                0.078202         0.001294
X39                0.088306         0.000191
X40                0.103438         0.000088
X41                0.126329         0.000163
X42                0.161608         0.000488
X43                0.217067         0.000000
X44                0.304378         0.000000
X45                0.432063         0.000000
X46                0.573363         0.000000
X47                0.654592         0.000000
X48                0.654544         0.000000
rho                0.789155         0.423884
v                 -0.849481         0.137036
p                  0.849481         0.105770

In [45]:
# pd.concat([dm, df1["LassoCV"].squeeze()], axis=1)

In [46]:
pd.concat([dm, df1], axis=1).set_index("features")

KeyError: "None of ['features'] are in the columns"