In [1]:
from scipy import stats
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

import seaborn as sns
#from matplotlib import subplots

import colorsys
import matplotlib

In [2]:
df = pd.read_csv("C:/Users/user/Feature_Selection/data/MT/DB6Tr.csv", sep=",", header=0)
df.head()

,T,T1,T2,T3,TVO2,TVCO,P,xCO2,xCO,xO2,xO,xC,Viscosity
0,6000.0,4000.0,2000.0,4000.0,4000.0,4000.0,101320.0,0.6,0.2,0.6,0.2,0.2,0.000150
1,16000.0,14000.0,12000.0,12000.0,14000.0,12000.0,101320.0,0.4,0.2,0.8,0.8,1.0,0.000344
2,20000.0,16000.0,18000.0,16000.0,16000.0,16000.0,101320.0,0.6,0.4,0.8,1.0,0.4,0.000388
3,12000.0,10000.0,8000.0,8000.0,10000.0,10000.0,101320.0,0.2,0.6,0.6,0.8,0.8,0.000283
4,16000.0,14000.0,14000.0,12000.0,12000.0,14000.0,101320.0,0.2,0.6,0.2,1.0,1.0,0.000369

In [7]:
Z = df.iloc[:, :13]
Z.shape

(67200, 13)

In [8]:
corr_matrix = Z.corr(method='pearson')

In [9]:
corr_matrix

,T,T1,T2,T3,TVO2,TVCO,P,xCO2,xCO,xO2,xO,xC,Viscosity
T,1.000000,0.979529,0.979495,0.979533,0.979395,0.979477,NaN,0.004941,0.001468,-0.000268,-0.003443,-0.002431,0.987038
T1,0.979529,1.000000,0.959390,0.959074,0.959654,0.959671,NaN,0.004807,0.002017,0.000727,-0.003628,-0.002088,0.966652
T2,0.979495,0.959390,1.000000,0.959443,0.959291,0.959755,NaN,0.003727,0.001539,-0.000309,-0.003613,-0.002143,0.966721
T3,0.979533,0.959074,0.959443,1.000000,0.959483,0.959456,NaN,0.004536,0.000821,-0.001316,-0.003404,-0.001864,0.966779
TVO2,0.979395,0.959654,0.959291,0.959483,1.000000,0.959704,NaN,0.006491,0.001190,-0.000693,-0.003156,-0.003077,0.966454
TVCO,0.979477,0.959671,0.959755,0.959456,0.959704,1.000000,NaN,0.005737,0.001081,-0.000165,-0.004234,-0.002708,0.966419
P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xCO2,0.004941,0.004807,0.003727,0.004536,0.006491,0.005737,NaN,1.000000,0.001785,-0.003457,-0.002540,0.001150,-0.096366
xCO,0.001468,0.002017,0.001539,0.000821,0.001190,0.001081,NaN,0.001785,1.000000,-0.007601,-0.001588,-0.010694,0.002303
xO2,-0.000268,0.000727,-0.000309,-0.001316,-0.000693,-0.000165,NaN,-0.003457,-0.007601,1.000000,0.005904,-0.001051,-0.034076
xO,-0.003443,-0.003628,-0.003613,-0.003404,-0.003156,-0.004234,NaN,-0.002540,-0.001588,0.005904,1.000000,-0.001142,0.071517
xC,-0.002431,-0.002088,-0.002143,-0.001864,-0.003077,-0.002708,NaN,0.001150,-0.010694,-0.001051,-0.001142,1.000000,0.050037
Viscosity,0.987038,0.966652,0.966721,0.966779,0.966454,0.966419,NaN,-0.096366,0.002303,-0.034076,0.071517,0.050037,1.000000