In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/transport/boltzmann/corr_df.csv", sep=",", header=0, index_col='index')
df.head()

             Conductivity
index
Pressure        -0.000290
Temperature      0.970970
X1              -0.603050
X2               0.257686
X3               0.461838

In [6]:
df = pd.read_csv("C:/Users/user/Feature_Selection/data/STS/transport/boltzmann/corr_df.csv", sep=",", header=0, index_col='index')
df.head()

             Conductivity
index
Pressure        -0.000290
Temperature      0.970970
X1              -0.603050
X2               0.257686
X3               0.461838

In [7]:
pd.concat([df,df ], axis=1)

              Conductivity  Conductivity
index
Pressure         -0.000290     -0.000290
Temperature       0.970970      0.970970
X1               -0.603050     -0.603050
X2                0.257686      0.257686
X3                0.461838      0.461838
X4                0.536302      0.536302
X5                0.565952      0.565952
X6                0.576514      0.576514
X7                0.577931      0.577931
X8                0.574671      0.574671
X9                0.568957      0.568957
X10               0.561971      0.561971
X11               0.554376      0.554376
X12               0.546554      0.546554
X13               0.538731      0.538731
X14               0.531038      0.531038
X15               0.523554      0.523554
X16               0.516323      0.516323
X17               0.509366      0.509366
X18               0.502692      0.502692
X19               0.496302      0.496302
X20               0.490192      0.490192
X21               0.484353      0.484353
X22               0.478775      0.478775
X23               0.473449      0.473449
X24               0.468362      0.468362
X25               0.463504      0.463504
X26               0.458864      0.458864
X27               0.454432      0.454432
X28               0.450197      0.450197
X29               0.446149      0.446149
X30               0.442281      0.442281
X31               0.438583      0.438583
X32               0.435047      0.435047
X33               0.431667      0.431667
X34               0.428435      0.428435
X35               0.425344      0.425344
X36               0.422389      0.422389
X37               0.419563      0.419563
X38               0.416863      0.416863
X39               0.414281      0.414281
X40               0.411815      0.411815
X41               0.409460      0.409460
X42               0.407212      0.407212
X43               0.405067      0.405067
X44               0.403022      0.403022
X45               0.401073      0.401073
X46               0.399219      0.399219
X47               0.397455      0.397455
X48               0.395779      0.395779
X49               0.133460      0.133460
Conductivity      1.000000      1.000000